// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqvVq46olSvcmEEMz0VtMVionrsKakQGQ',
    appId: '1:178847742267:web:d2bc2448ab36fa85a41f1e',
    messagingSenderId: '178847742267',
    projectId: 'lathamarriagebureau-810cd',
    authDomain: 'lathamarriagebureau-810cd.firebaseapp.com',
    storageBucket: 'lathamarriagebureau-810cd.firebasestorage.app',
    measurementId: 'G-CPECZQTECZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH-QCUZOQfiznzOodrnPtHJQztiTZDfUU',
    appId: '1:178847742267:android:82b920c4200d9e6ca41f1e',
    messagingSenderId: '178847742267',
    projectId: 'lathamarriagebureau-810cd',
    storageBucket: 'lathamarriagebureau-810cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs8Y2QeHQ1ida8YyrKQepGugWH3jXLQHI',
    appId: '1:178847742267:ios:b64e003905be6c4ba41f1e',
    messagingSenderId: '178847742267',
    projectId: 'lathamarriagebureau-810cd',
    storageBucket: 'lathamarriagebureau-810cd.firebasestorage.app',
    androidClientId: '178847742267-rei8g017ul30tlr08jn9jrdmhnmfenaf.apps.googleusercontent.com',
    iosClientId: '178847742267-rcl7jldfporfik6thh5d9561kci2k677.apps.googleusercontent.com',
    iosBundleId: 'com.example.lathaMarriageBureau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs8Y2QeHQ1ida8YyrKQepGugWH3jXLQHI',
    appId: '1:178847742267:ios:b64e003905be6c4ba41f1e',
    messagingSenderId: '178847742267',
    projectId: 'lathamarriagebureau-810cd',
    storageBucket: 'lathamarriagebureau-810cd.firebasestorage.app',
    androidClientId: '178847742267-rei8g017ul30tlr08jn9jrdmhnmfenaf.apps.googleusercontent.com',
    iosClientId: '178847742267-rcl7jldfporfik6thh5d9561kci2k677.apps.googleusercontent.com',
    iosBundleId: 'com.example.lathaMarriageBureau',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqvVq46olSvcmEEMz0VtMVionrsKakQGQ',
    appId: '1:178847742267:web:d2bc2448ab36fa85a41f1e',
    messagingSenderId: '178847742267',
    projectId: 'lathamarriagebureau-810cd',
    authDomain: 'lathamarriagebureau-810cd.firebaseapp.com',
    storageBucket: 'lathamarriagebureau-810cd.firebasestorage.app',
    measurementId: 'G-CPECZQTECZ',
  );
}
